### ISSUE TITLE
Installation incomplete

### ISSUE THREAD

**Issue by iCRON862** [Dcnigma/DC-uLaunch_Updater#1]
When i have installed uLaunch success i can't boot AMS (exception handler) and in AMS's "title" folder the TitleID folders 01008BB00013C000 and 010000000000100B are completley missing. What happened here?

**Comment by Dcnigma** [comment]
Hey DevCoud18,  
That is strange few questions:   

-Did you do a fresh install? (Never tried uLaunch before)   
-Did you see it unzipping after download?  
-Did your root of your sd hold /SDout/titles/01008BB00013C000 and 010000000000100B  
  and 2 other folders of course.  
  
I can think up 2 things that happened.  

-1) Fresh install never used uLaunch.   
So folders 01008BB00013C000 and 010000000000100B   
Did not exist at install so could be moved.
 
2)Or you have a hidden folders .01008BB00013C000 and .010000000000100B
This happened one time to me.

Testing theory, one now

**Comment by Dcnigma** [comment]
And I think we found the problem ;-)
Thanks.
Will change it in the code that it will create those 2 folders before moving.

**Comment by Dcnigma** [comment]
Update your app and it is fixed. 
Just tested clean AMS install, 5 titles installed and now it works. 
Also for a fresh install, I made this program because I didn't want swap or FTP the whole time.
But I did add those folders first they didn't get created at boot like those other 2 folders.
Thanks

**Comment by Dcnigma** [comment]
It started out as an updater not an installer.
But thanks for reporting will close this after you confirm its working and you did a fresh install.

Cheers

**Comment by iCRON862** [comment]
Thx comfirmed the fix👍
